### ISSUE TITLE
Issue in if statements?

### ISSUE THREAD

**Issue by anuprulez** [MasterprojectRK/Hi-cGAN#1]
https://github.com/MasterprojectRK/HiC-GAN/blob/5a1ef31f11ea83d7e8b7b065b9f19a03439349a4/hicGAN.py#L134

https://github.com/MasterprojectRK/HiC-GAN/blob/5a1ef31f11ea83d7e8b7b065b9f19a03439349a4/hicGAN.py#L150

Can you check these `if` statements and the actions inside these? One `if` statement seems to already contain the other one and the actions are same inside both the `if` statements.

Please close this issue if the code blocks are fine.

Thanks!

**Comment by MasterprojectRK** [comment]
Functionally, the code seems ok.
Line134: 
The idea here is to perform "pop" on the second last layer, depending on input size.
If -inf < input size < 128, pop is performed twice, and if 128 <= input size < 256, it is performed once.

Line150:
In this case, pop is performed on the third layer; again twice, if -inf < inputs size  < 128, and once, if 128 <= input size < 256.

Example:
import numpy as np
np1 = list(np.arange(10))
np2 = np1.copy()
np1 = np1[:-2] + np1[-1:] #[0, 1, 2, 3, 4, 5, 6, 7, 9]
np1 = np1[:-2] + np1[:-2] #[0, 1, 2, 3, 4, 5, 6, 9]
np2 = np2[:2] + np2[3:]  #[0, 1, 3, 4, 5, 6, 7, 8, 9]
np2 = np2[:2] + np2[3:] #[0, 1, 4, 5, 6, 7, 8, 9]

Simple pop of the first/last layers seems not good, since these are special in terms of dropout and batch normalization.
As dropout layers are the sole source of noise for the GAN, it seems not good to remove two of them even when reducing
window size.
